import { PrimaryKey } from '../types';

export function PrimaryKey(autoGenerated?: boolean) {
	return (target: any, key: string) => {
		if (!target.$$primaryKeys) {
			target.$$primaryKeys = [];
		}
		let pkey: PrimaryKey = { pKey: key };
		pkey.generated = typeof autoGenerated === 'boolean' ? autoGenerated : true;
		target.$$primaryKeys.push(pkey);
	};
}